<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="css/styles.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    <script src="https://kit.fontawesome.com/486886617b.js" crossorigin="anonymous"></script>
</head>
<body>
<section id="dessin">
    <canvas id="feuille" width="400" height="400" >


    </canvas>
    <div id="palette">
        <div data-color="black"></div>
        <div data-color="red"></div>
        <div data-color="orange"></div>
        <div data-color="yellow"></div>
        <div data-color="green"></div>
        <div data-color="lightblue"></div>
        <div data-color="blue"></div>
        <div data-color="purple"></div>
        <div> <i class="fa-solid fa-palette"></i>  <input  id = "colorPicker" type="color" ></div>

    </div>
    <div id="outils">
        <div id ="gomme"><i class="fa-solid fa-eraser"></i></div>

        <div id="selectedColor"> </div>
        <div id="basicStroke"> <i class="fa-solid fa-pencil"></i> </div>
        <div id="smallerStroke"> <i class="fa-solid fa-down-long"></i> </div>
        <div id="biggerStroke"> <i class="fa-solid fa-up-long"></i></div>



    </div>
</section>
<div class="formPart">
    <button id="displayForm">Envoyer la carte</button>
</div>

<form class ="formHidden" method ="POST" action="form.php">
    <div class="form-groupe">
        <label for="emailDesigner">Votre mail</label>
        <input type="email" id="emailDesigner" name="emailDesigner" placeholder="Votre mail" required>
        <?php if (isset($errors['emailDesigner'])): ?>
        <p class="error"><?=$errors['emailDesigner'];?></p>

        <?php endif; ?>

    </div>

    <div class="form-groupe">
        <label for="emailRecipient">Email de votre destinataire</label>
        <input type="email" id="emailRecipient" name="emailRecipient" placeholder="Votre mail" required>
        <?php if (isset($errors['emailRecipient'])): ?>
        <p class="error"><?=$errors['emailRecipient'];?></p>
        <?php endif; ?>

    </div>

    <div class="form-groupe">
        <label for="message">Votre message</label>
        <textarea id="message" placeholder="Votre message" name ="message" cols="50" rows="10" required></textarea>

    </div>
    <div class="form-groupe flex-type">
        <input type="checkbox" id="copy" name="copy[]" value="yes">
        <label for="copy"> Voulez vous recevoir une copie du mail?</label>


    </div>

    <div class="form-groupe">

        <input type="submit" name="submit" id="submit" value="Envoyer" >
    </div>
<input type="hidden" id="formAndDraw"name="image" >




</form>
<script src="index.js" type="module"></script>
<!--<script src="modules/form.js"></script>
<script src="modules/Dessin.js"></script>
<script src="modules/App.js"></script>-->

</body>
</html>